### ISSUE TITLE
Would it better to sort along time?

### ISSUE THREAD

**Issue by CiaoHe** [QizhiPei/Awesome-Biomolecule-Language-Cross-Modeling#1]
Thx for your great job. Would it be easier to follow if articles in various fields were arranged in chronological order? If need help, glad to join this project.

**Comment by QizhiPei** [comment]
Thanks for your interest and suggestion! 
Currently, within each subdomain, the articles are organized by year and published track.
We welcome you to contribute by submitting a pull request if you have suggestions for a better format or order. Look forward to your help and contribution.
