### ISSUE TITLE
Add dataset of GIMLET

### ISSUE THREAD

**Issue by zhao-ht** [QizhiPei/Awesome-Biomolecule-Language-Cross-Modeling#2]
The work GIMLET: A Unified Graph-Text Model for Instruction-Based Molecule Zero-Shot Learning also releases instruction datasets for both pretraining and testing available at their github code https://github.com/zhao-ht/GIMLET and on huggingface:  https://huggingface.co/datasets/haitengzhao/molecule_property_instruction. Hope this can be added to the dataset list ^^

**Comment by QizhiPei** [comment]
Thx for your suggestion. We have added GIMLET dataset to the dataset list~
