### ISSUE TITLE
Add several datasets from https://github.com/kjappelbaum/awesome-chemistry-datasets

### ISSUE THREAD

**Issue by CiaoHe** [QizhiPei/Awesome-Biomolecule-Language-Cross-Modeling#3]
You can refer to kjappelbaum's [awesome-chemistry-datasets](https://github.com/kjappelbaum/awesome-chemistry-datasets) to add more datasets

Like:
text datasets
* [BC5CDR](https://paperswithcode.com/dataset/bc5cdr):1500 PubMed articles with 4409 annotated chemicals, 5818 diseases and 3116 chemical-disease interactions (named entity recognition)
* [BioCreative V](https://biocreative.bioinformatics.udel.edu/tasks/biocreative-v/track-3-cdr/): BC5CDR corpus consists of 1500 PubMed articles with 4409 annotated chemicals, 5818 diseases and 3116 chemical-disease interactions.
* [Elsevier Corpus](https://elsevier.digitalcommonsdata.com/datasets/zm33cdndxs/3): This is a corpus of 40k (40,001) open access (OA) CC-BY articles from across Elsevier’s journals represent the first cross-discipline research of data at this scale to support NLP and ML research.
* [Europe PMC](https://europepmc.org/downloads) - Bulk download of full text and SI of > 5 million articles.
...

**Comment by QizhiPei** [comment]
Thanks for your recommendation. We will refer to it to add more datasets.
